### Tutorial 9- Python Pandas Tutorials- Part 1

In Part we are going to learn about
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

![](panda.JPG)

In [ ]:
#!pip install pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
## Create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1",
                                                      "Row2","Row3",
                                                      "Row4","Row5"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             "Column4"])

In [4]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [5]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [8]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [9]:
##Indexing
## columnname,rowindex[loc],rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
##columnname
type(df['Column1'])

pandas.core.series.Series

In [11]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [12]:
##using row index name loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [13]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [14]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [15]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [16]:
##convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [17]:
## Basic operations
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [18]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1",
                                                      "Row2"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])

In [19]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [20]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [21]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [22]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [23]:
df['Column3'].value_counts()

Column3
2    1
4    1
Name: count, dtype: int64

In [24]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [25]:
df['Column2'].unique()

array([nan,  3.])

In [26]:
df[df['Column2']>2]

Column1  Column2  Column3
Row2        1      3.0        4