![](numpy.JPG)

![](APP.JPG)

### Properties of Numpy
* Homogenous
* Only be Number(Number,Float,Complex) and it can hold strings but we never use numpy that way
* Fixed item size

![](Creating.JPG)

In [1]:
#### creating numpy/nd arrays
import numpy as np

In [5]:
arr1= np.array([1,2,5,7,8])
arr1

array([1, 2, 5, 7, 8])

In [11]:
print(type(arr1))

<class 'numpy.ndarray'>
1


In [7]:
arr2= np.array([[1,2,5,7,8],[5,6,7,8,8]])
arr2

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

In [38]:
print(type(arr2))

<class 'numpy.ndarray'>


In [13]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [25]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [26]:
arr8 = arr2.copy()
arr8

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

### Properties and Attributes
![](prop.JPG)


In [28]:
arr1.shape

(5,)

In [30]:
arr2

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

In [29]:
arr2.shape

(2, 5)

In [36]:
arr9 = np.array([[[1,3],[3,4]],[[5,6],[4,6]]])
arr9

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [4, 6]]])

In [37]:
arr9.shape

(2, 2, 2)

In [39]:
arr1.ndim

1

In [40]:
arr3.ndim

2

In [41]:
arr9.ndim

3

In [42]:
arr1.size

5

In [43]:
arr6.size

6

In [44]:
arr9.size

8

In [46]:
arr9.itemsize

4

In [48]:
arr7.itemsize

8

In [51]:
arr9.dtype

dtype('int32')

In [52]:
arr9.astype('float')

array([[[1., 3.],
        [3., 4.]],

       [[5., 6.],
        [4., 6.]]])

### List Vs Array
* Faster
* Convenient
* Less Memory

In [58]:
lista=range(100)
arr11 = np.arange(100)

In [59]:
import sys
print(sys.getsizeof(34)*len(lista))

2800


In [60]:
print(arr11.itemsize*arr11.size)

400


In [61]:
import time

In [67]:
x=range(100000)
y=range(100000,200000)
start_time = time.time()
c= [x+y for x,y in zip(x,y)]
print(time.time()-start_time)

0.011512994766235352


In [68]:
a=np.arange(100000)
b=np.arange(100000,200000)
start_time = time.time()
c=a+b
print(time.time()-start_time)

0.0015978813171386719


In [70]:
arr12 = np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Indexing ,Slicing and Iteration

In [71]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
arr1[2]

2

In [75]:
arr1[2:4]

array([2, 3])

In [77]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
arr12[2]

array([ 8,  9, 10, 11])

In [78]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [79]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [83]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [84]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [85]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [86]:
for i in arr12:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [87]:
# apply filter on every pixel of image
for i in np.nditer(arr12):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [88]:
new_arr1 = np.array([1,2,3,4,5,6])
new_arr2 = np.array([4,5,6,7,8,9])

In [95]:
new_arr3 = np.arange(6).reshape(2,3)
new_arr4 = np.arange(6).reshape(3,2)

In [98]:
newarr_5 = new_arr3.dot(new_arr4)
newarr_5

array([[10, 13],
       [28, 40]])

In [91]:
new_arr1.max()

6

In [92]:
new_arr1.min()

1

In [99]:
newarr_5.min()

10

In [100]:
newarr_5.min(axis=0)

array([10, 13])

In [102]:
newarr_5.max(axis=0)

array([28, 40])