![](numpy.JPG)

![](APP.JPG)

### Properties of Numpy
* Homogenous
* Only be Number(Number,Float,Complex) and it can hold strings but we never use numpy that way
* Fixed item size

![](Creating.JPG)

In [11]:
#### creating numpy/nd arrays
import numpy as np

In [12]:
arr1= np.array([1,2,5,7,8])
arr1

array([1, 2, 5, 7, 8])

In [13]:
print(type(arr1))

<class 'numpy.ndarray'>


In [14]:
arr2= np.array([[1,2,5,7,8],[5,6,7,8,8]])
arr2

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

In [15]:
print(type(arr2))

<class 'numpy.ndarray'>


In [16]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [20]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr8 = arr2.copy()
arr8

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

### Properties and Attributes
![](prop.JPG)


In [22]:
arr1.shape

(5,)

In [23]:
arr2

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

In [24]:
arr2.shape

(2, 5)

In [25]:
arr9 = np.array([[[1,3],[3,4]],[[5,6],[4,6]]])
arr9

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [4, 6]]])

In [26]:
arr9.shape

(2, 2, 2)

In [27]:
arr1.ndim

1

In [28]:
arr3.ndim

2

In [29]:
arr9.ndim

3

In [30]:
arr1.size

5

In [31]:
arr6.size

6

In [32]:
arr9.size

8

In [33]:
arr9.itemsize

4

In [34]:
arr7.itemsize

8

In [35]:
arr9.dtype

dtype('int32')

In [36]:
arr9.astype('float')

array([[[1., 3.],
        [3., 4.]],

       [[5., 6.],
        [4., 6.]]])

### List Vs Array
* Faster
* Convenient
* Less Memory

In [37]:
lista=range(100)
arr11 = np.arange(100)

In [38]:
import sys
print(sys.getsizeof(34)*len(lista))

2800


In [39]:
print(arr11.itemsize*arr11.size)

400


In [40]:
import time

In [41]:
x=range(100000)
y=range(100000,200000)
start_time = time.time()
c= [x+y for x,y in zip(x,y)]
print(time.time()-start_time)

0.010992765426635742


In [42]:
a=np.arange(100000)
b=np.arange(100000,200000)
start_time = time.time()
c=a+b
print(time.time()-start_time)

0.0009996891021728516


In [43]:
arr12 = np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Indexing ,Slicing and Iteration

In [44]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
arr1[2]

5

In [46]:
arr1[2:4]

array([5, 7])

In [47]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
arr12[2]

array([ 8,  9, 10, 11])

In [49]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [50]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [51]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [52]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [53]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
for i in arr12:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [55]:
# apply filter on every pixel of image
for i in np.nditer(arr12):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### Numpy Operation

In [56]:
new_arr1 = np.array([1,2,3,4,5,6])
new_arr2 = np.array([4,5,6,7,8,9])

In [57]:
new_arr1+new_arr2

array([ 5,  7,  9, 11, 13, 15])

In [58]:
new_arr1-new_arr2

array([-3, -3, -3, -3, -3, -3])

In [59]:
new_arr1*new_arr2

array([ 4, 10, 18, 28, 40, 54])

In [60]:
new_arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [61]:
new_arr1>3

array([False, False, False,  True,  True,  True])

In [62]:
new_arr3 = np.arange(6).reshape(2,3)
new_arr4 = np.arange(6).reshape(3,2)

In [63]:
new_arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
new_arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [80]:
new_arr5 = new_arr3.dot(new_arr4)
new_arr5

array([[10, 13],
       [28, 40]])

In [82]:
new_arr4.dot(new_arr1)

ValueError: shapes (3,2) and (6,) not aligned: 2 (dim 1) != 6 (dim 0)

In [90]:
new_arr1.max()

6

In [91]:
new_arr1.min()

1

In [92]:
new_arr5.min()

10

In [93]:
new_arr5.min(axis=0)

array([10, 13])

In [88]:
new_arr5.max(axis=0)

array([28, 40])

In [94]:
new_arr5.max(axis=1)

array([13, 40])

In [95]:
new_arr5.sum(axis=0)

array([38, 53])

In [96]:
new_arr5.mean()

22.75

In [97]:
new_arr5.std()

12.07010770457331

In [98]:
np.sin(new_arr5)

array([[-0.54402111,  0.42016704],
       [ 0.27090579,  0.74511316]])

In [99]:
np.median(new_arr5)

20.5

In [102]:
np.mean(new_arr5)

22.75

In [103]:
np.exp(new_arr5)

array([[2.20264658e+04, 4.42413392e+05],
       [1.44625706e+12, 2.35385267e+17]])

In [104]:
np.sqrt(new_arr5)

array([[3.16227766, 3.60555128],
       [5.29150262, 6.32455532]])

### Reshaping Numpy Arrays

In [106]:
new_arr5

array([[10, 13],
       [28, 40]])

In [107]:
new_arr5.ndim

2

In [108]:
# convert higher dimensional to one dimension
new_arr5.ravel()

array([10, 13, 28, 40])

In [111]:
arr8

array([[1, 2, 5, 7, 8],
       [5, 6, 7, 8, 8]])

In [112]:
arr8.transpose()

array([[1, 5],
       [2, 6],
       [5, 7],
       [7, 8],
       [8, 8]])

In [113]:
new_arr6 = np.arange(12,18).reshape(2,3)
new_arr6

array([[12, 13, 14],
       [15, 16, 17]])

In [119]:
np.hstack((new_arr3,arr8))

array([[0, 1, 2, 1, 2, 5, 7, 8],
       [3, 4, 5, 5, 6, 7, 8, 8]])

In [124]:
np.vstack((arr5,arr5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [125]:
np.hsplit(new_arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [126]:
np.vsplit(new_arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

### Fancy Indexing

In [128]:
new_arr7 = np.arange(24).reshape(6,4)

In [129]:
new_arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
# 1,3rd,5th row
new_arr7[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])